### ISSUE TITLE
Update repo description and readme to include link to live wallet docs site

### ISSUE THREAD

**Issue by lukemulks** [brave/brave-wallet-docs#18]
Currently, we reference the service that we use for the dev docs for Wallet, but do not include the actual URL to the live wallet docs website. 

Suggest adding this: 

Developer documentation for the Brave Wallet https://wallet-docs.brave.com/

In the following locations: 
 - In the repository metadata, for the repository description
 - At the top of the Readme in the repo, under the Welcome section https://github.com/brave/brave-wallet-docs#website 
 
I ran an in-page search, and wasn't able to locate the live site link. A dev let me know they had a hard time finding this on Twitter, so providing a link to the live site for the docs may help folks that discover this from github if they're searching for our docs, and help with partner outreach. 

I'd just edit myself and PR, but I don't believe I have the ability to for this particular repo. 

cc: @bbondy

**Comment by bbondy** [comment]
Good idea.  Fixed and deployed.
